
                elementtypelist: [
                    { id: 0, label: '無' },
                    { id: 1, label: '火' },
                    { id: 2, label: '水' },
                    { id: 3, label: '風' },
                    { id: 4, label: '地' },
                    { id: 5, label: '毒' },
                    { id: 6, label: '聖' },
                    { id: 7, label: '暗' },
                    { id: 8, label: '念' },
                    { id: 9, label: '不死' }
                ],
                effecttypelist: [
                    { label: 'STR', id: 'STR', totalvalue: '', opersymbol: '\+', suffixsymbol: '' },
                    { label: 'AGI', id: 'AGI', totalvalue: '', opersymbol: '\+', suffixsymbol: '' },
                    { label: 'VIT', id: 'VIT', totalvalue: '', opersymbol: '\+', suffixsymbol: '' },
                    { label: 'INT', id: 'INT', totalvalue: '', opersymbol: '\+', suffixsymbol: '' },
                    { label: 'DEX', id: 'DEX', totalvalue: '', opersymbol: '\+', suffixsymbol: '' },
                    { label: 'LUK', id: 'LUK', totalvalue: '', opersymbol: '\+', suffixsymbol: '' },
                    { label: '全能力', id: 'AllStatus', totalvalue: '', opersymbol: '\+', suffixsymbol: '' },

                    { label: 'Atk', id: 'Atk', totalvalue: '', opersymbol: '\+', suffixsymbol: '' },
                    { label: 'Atk %', id: 'AtkPercent', totalvalue: '', opersymbol: '\+', suffixsymbol: '\%' },
                    { label: '物理種族 %', id: 'RaceAtkPercent', totalvalue: '', opersymbol: '\+', suffixsymbol: '\%' },
                    { label: '物理體型 %', id: 'SizeAtkPercent', totalvalue: '', opersymbol: '\+', suffixsymbol: '\%' },
                    { label: '對屬性魔物Atk %', id: 'ElementalAtkPercent', totalvalue: '', opersymbol: '\+', suffixsymbol: '\%' },
                    { label: '物理階級 %', id: 'LevelAtkPercent', totalvalue: '', opersymbol: '\+', suffixsymbol: '\%' },
                    { label: '物理特定怪 %', id: 'MonsterAtkPercent', totalvalue: '', opersymbol: '\+', suffixsymbol: '\%' },
                    { label: '暴傷 %', id: 'CriDamagePercent', totalvalue: '', opersymbol: '\+', suffixsymbol: '\%' },
                    { label: '遠傷 %', id: 'RangedDamagePercent', totalvalue: '', opersymbol: '\+', suffixsymbol: '\%' },
                    { label: '無視物理防禦 %', id: 'BypassDEFPercent', totalvalue: '', opersymbol: '\+', suffixsymbol: '\%' },

                    { label: 'Matk', id: 'Matk', totalvalue: '', opersymbol: '\+', suffixsymbol: '' },
                    { label: 'Matk %', id: 'MatkPercent', totalvalue: '', opersymbol: '\+', suffixsymbol: '\%' },
                    { label: '魔法種族 %', id: 'RaceMatkPercent', totalvalue: '', opersymbol: '\+', suffixsymbol: '\%' },
                    { label: '魔法體型 %', id: 'SizeMatkPercent', totalvalue: '', opersymbol: '\+', suffixsymbol: '\%' },
                    { label: '魔法階級 %', id: 'LevelMatkPercent', totalvalue: '', opersymbol: '\+', suffixsymbol: '\%' },
                    { label: '對屬性魔物Matk %', id: 'ElementalMatkPercent', totalvalue: '', opersymbol: '\+', suffixsymbol: '\%' },
                    { label: '屬性魔法 %', id: 'ElementalMagicPercent', totalvalue: '', opersymbol: '\+', suffixsymbol: '\%' },
                    { label: '魔法特定怪 %', id: 'MonsterMatkPercent', totalvalue: '', opersymbol: '\+', suffixsymbol: '\%' },
                    { label: '無視魔法防禦 %', id: 'BypassMDEFPercent', totalvalue: '', opersymbol: '\+', suffixsymbol: '\%' },

                    { label: '技能增傷 %', id: 'SkillDamagePercent', totalvalue: '0', opersymbol: '\+', suffixsymbol: '\%' },
                    { label: '技能獨延', id: 'CDTime', totalvalue: '', opersymbol: '\-', suffixsymbol: '\s' },
                    { label: '技能後(共)延%', id: 'GCDPercent', totalvalue: '', opersymbol: '\-', suffixsymbol: '\%' },
                    { label: '變詠 %', id: 'VariableCastPercent', totalvalue: '', opersymbol: '\-', suffixsymbol: '\%' },
                    { label: '指定技能變詠 %', id: 'SPSkillVariableCastPercent', totalvalue: '', opersymbol: '\-', suffixsymbol: '\%' },
                    { label: '固詠', id: 'FixedCast', totalvalue: '', opersymbol: '\-', suffixsymbol: 's' },
                    { label: '固詠 %', id: 'FixedCastPercent', totalvalue: '', opersymbol: '\-', suffixsymbol: '\%' },
                    { label: 'ASPD', id: 'ASPD', totalvalue: '', opersymbol: '\+', suffixsymbol: '' },
                    { label: '攻擊後延%', id: 'AspdPercent', totalvalue: '', opersymbol: '\-', suffixsymbol: '\%' },
                    { label: '暴擊率 %', id: 'Cri', totalvalue: '', opersymbol: '\+', suffixsymbol: '\%' },

                    { label: 'HP %', id: 'HPPercent', totalvalue: '0', opersymbol: '\+', suffixsymbol: '\%' },
                    { label: 'HP', id: 'HP', totalvalue: '0', opersymbol: '\+', suffixsymbol: '' },
                    { label: 'SP %', id: 'SPPercent', totalvalue: '0', opersymbol: '\+', suffixsymbol: '\%' },
                    { label: 'SP', id: 'SP', totalvalue: '0', opersymbol: '\+', suffixsymbol: '' },
                    
                    { label: '無視體型攻擊', id: 'WeaponPerfection', totalvalue: '0', opersymbol: '', suffixsymbol: '' },
                    { label: '浸透勁效果', id: 'WeaponOccult', totalvalue: '0', opersymbol: '', suffixsymbol: '' },
                ]